apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskapp
  name: flask-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 31200
  selector:
    app: flaskapp
  type: NodePort
